typedef struct monde Monde;
void afficherMonde(Monde *m);
Monde *creerMonde();
Unite* getUnite(Monde *m, int x, int y);
int deplaceUnite(Monde *m, int x, int y, int newX, int newY);
void initialiserMonde(Monde *m);
void initialiserMonde(Monde *m);
int partieFinie(Monde *m);
int get_nb_vivant(Monde *m, char couleur);
void MLV_afficherMonde(Monde *m);
Unite *MLV_getUnite_from_mouse(Monde *m, int *x, int *y);